// Writes src/deck/qr.ts: the lesson URL as an SVG path of dark modules.
import { writeFileSync } from "node:fs";
import QRCode from "qrcode";

const url = "https://appiest.github.io/duolingo-if/";
const qr = QRCode.create(url, { errorCorrectionLevel: "M" });
const { size, data } = qr.modules;
let path = "";
for (let row = 0; row < size; row += 1) {
  for (let column = 0; column < size; column += 1) {
    if (data[row * size + column]) path += `M${column} ${row}h1v1h-1z`;
  }
}
writeFileSync(
  new URL("../src/deck/qr.ts", import.meta.url),
  `// Generated by scripts/make-qr.mjs. Do not edit by hand.\nexport const lessonUrl = ${JSON.stringify(url)};\nexport const qrSize = ${size};\nexport const qrPath = ${JSON.stringify(path)};\n`,
);
console.log(`QR code for ${url}: ${size}x${size} modules`);
